### ISSUE TITLE
POST requests don't work

### ISSUE THREAD

**Issue by Roboxkin** [momo-AUX1/mango#1]
Hello! Any post request returns a 405 error

```
from mango import route
from mango import run
from mango import set_routes
from mango import get_json
@route('/')
def index():
    return "This home page, hello user!!!"

@route('/post')
def post(data):
    user = get_json(data)
    return f"Hello, {user['name']}!"

run(host='localhost', port=8083, debug_mode=False)
```

**Comment by momo-AUX1** [comment]
Hello, make sure to have updated the framework as it is being updated often and this could have been fixed already. 405 usually indicates not allowed make sure to set the request headers to application/json in your request. Mango supports basic forms, Mutlipart and JSON anything else will return 405 it is working as intended.



```
from mango import route
from mango import run
from mango import set_routes
from mango import get_json
@route('/')
def index():
    return "This home page, hello user!!!"

@route('/post')
def post(data):
    user = get_json(data)
    return f"Hello, {user['name']}!"

run(host='127.0.0.1', port=8084, debug_mode=False)
```


and an example request post that sends JSON:

import requests

req = requests.post("http://127.0.0.1:8084", json={"name":"test"})

print(req.text)

**Comment by Roboxkin** [comment]
Hello! Thank you very much for the answer !
Everything works now!
Sincerely

**Comment by momo-AUX1** [comment]
No problem please do report any problems and i'll fix them 😃
