### ISSUE TITLE
Adding Auto Reloader

### ISSUE THREAD

**Issue by Vidito** [momo-AUX1/mango#2]
Do you plan to add an auto-reloader/refresh option so you won't have to restart the server with every change in source code?

**Comment by momo-AUX1** [comment]
Hello Vidito,

Of course i actually started looking into it recently by taking the flask example, i'll add it in a new update today or tomorrow that includes an auto refresh when in dev mode.

**Comment by momo-AUX1** [comment]
I released the update, i will be closing this issue now. Please do not hesitate to open a new one for new features and/or bugs you may encounter.
